### ISSUE TITLE
[ЖЕЛАЕМОЕ ИСПРАВЛЕНИЕ] Компактное преобразование в ассемблер для if без else для одной команды

### ISSUE THREAD

**Issue by Vadimatorik** [trol73/the-rat-avr#14]
Вот пример метода, который принимает бит данных uart-а и помещает в программный сдвиговый регистр как старший бит. Предварительно сдвинув прошлое значение вправо:
```
inline proc rx_data_bit() {
    udr >>= 1                        ; Биты идут от младшего к старшему.
    if (tx->pin) {                   ; Если 1 на входе, то он теперь
        udr[7] = 1                   ; самый старший.
    }                                ; А 0 и так после сдвига.
}
```
Тут по сути можно не делать ветвления как такового. А сделать "пропустить если 0". Тогда никаких переходов по сути писать не нужно было бы. Есть в планах проработать эту конструкцию?

Сейчас она перетекает в:
```
0000006a: sbis	22, 0
0000006c: rjmp	tim_0_ovf_irq_handler_in_in_in_in_in_in_in_in_in_in_inl_inl_in_in_in_in_in_i_inl_i_inl@if_end@29 (tim_0_ovf_irq_handler@tim_0_ovf_irq_handler_in_in_in_in_in_in_in_in_in_in_inl_inl_in_in_in_in_in_i_inl_i_inl@if_end@29)
0000006e: sbr	R21, 128
```
Что кушает больше кода, чем хотелось бы)

**Comment by trol73** [comment]
Тут для компактности нужно использовать следующую запись:
`if (tx->pin) udr[7] = 1`

Фигурные скобки в if всегда приводят к созданию блока. А наличие двух вариантов синтаксиса (со скобками и без) позволяет глядя на код сразу сказать, скомпилируется ли он компактным образом.
