### ISSUE TITLE
[ОШИБКА] Собирается, но не собирается

### ISSUE THREAD

**Issue by Vadimatorik** [trol73/the-rat-avr#15]
Хотел не писать 2 цикла, а использовать один. Как в примере:
```
proc delay_ms_long() { 
    loop (r25.r24) {
        nop
    }
    ret
}

```

Получаю:
```
Compile /home/vadimatorik/proj/rat/demo_led_flasher/src/main.art
ERROR: /home/vadimatorik/proj/rat/demo_led_flasher/src/./../driver_attiny13a/time.art:25:11: Register pair expected but R24 found
Compilation error!
Done.
Done

```

При этом - вроде даже собирается:
![image](https://user-images.githubusercontent.com/14297516/223558129-17284151-dc08-41bd-b263-8a58ee1d70a2.png)

**Comment by Vadimatorik** [comment]
В эту же степь вот еще прикол:
```
proc delay_ms_long(ms: X) { 
    loop (ms) {
        rcall delay_1_ms()
    }
    ret
}

```

И из кода:
```
rcall delay_ms_long(500)
```

Судя по ассемблеру - собирается. Причем верно. Однако размер не показывает и ошибку сыпет. Хотя по логике вроде все верно.

**Comment by Vadimatorik** [comment]
![image](https://user-images.githubusercontent.com/14297516/223558792-c0e07df6-a977-4aa1-a90d-1b080e60c16e.png)
![image](https://user-images.githubusercontent.com/14297516/223558822-3d47f4ab-be4a-4aca-8396-9fc516f2ecbb.png)

**Comment by trol73** [comment]
Спасибо, исправил. Сегодня выложу сборку (отпишусь в ветке обсуждения)
