### ISSUE TITLE
[ОШИБКА] Value too big: 3200 Compilation error Done

### ISSUE THREAD

**Issue by Vadimatorik** [trol73/the-rat-avr#16]
Не удается собрать такой код:
```
proc delay_1_ms() {
    loop (X = 3200) {
    }
    ret
}
```

Вообще.
![image](https://user-images.githubusercontent.com/14297516/223560511-a9c6d4d2-bc8c-499e-b706-1dab6df50b26.png)

Но если попробую так:
```
proc delay_1_ms() {
    XL = low(3200)
    XH = high(3200)
    loop (X) {
    }
    ret
}
```

То будет ошибка:
```
Compile /home/vadimatorik/proj/rat/demo_led_flasher/src/main.art
ERROR: /home/vadimatorik/proj/rat/demo_led_flasher/src/./../driver_attiny13a/time.art:10:11: Register pair expected but R26 found
Compilation error!
Done.
Done

```

![image](https://user-images.githubusercontent.com/14297516/223560430-21bdac95-8ea8-4ee6-b1c1-99aff67adf20.png)

**Comment by trol73** [comment]
По сути это дубликат https://github.com/trol73/the-rat-avr/issues/15
