### ISSUE TITLE
[ОШИБКА] Нет адекватного ответа на -h -help -?

### ISSUE THREAD

**Issue by Vadimatorik** [trol73/the-rat-avr#18]
Ввожу:
```
ratc -h
```

Получаю:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.getAbsolutePath()" because the return value of "java.io.File.getParentFile()" is null
	at ru.trolsoft.therat.RatKt.main(rat.kt:109)
```

Базовый help-то надо бы отображать начать.

**Comment by Vadimatorik** [comment]
Сюда же. Просто ratc - не имеет \n в конце вывода. 
![image](https://user-images.githubusercontent.com/14297516/223866675-f07301c2-c8f6-46d6-bfd8-a8413924d803.png)

**Comment by trol73** [comment]
help отображается по ключу "-help", "-h" - это неправильно (и, да, тот же gcc, например, "-h" не понимает).
В итоге компилятор пытается открыть файл "-h", не находит его и падает (точнее, он не находит он директорию, в которой надо искать локальный конфиг .ratc).
Но выдавать тут NPE совсем плохо, исправил (в следующей сборке будет, вместе с "\n" в usage).

**Comment by Vadimatorik** [comment]
Ладно, gcc и вправду -h не переваривает. Странный он. Ну ок.
