### ISSUE TITLE
[ЖЕЛАЕМОЕ ИСПРАВЛЕНИЕ] Выводить в gcc листенге исходные значения регистров и чисел

### ISSUE THREAD

**Issue by Vadimatorik** [trol73/the-rat-avr#6]
Если было 0x10 в коде art - писать так же и в листинге asm. Если было SPL - так и писать, а не asm. Но при этом в начала надо определить все кастомные переменные. А те, что родные (описания регистров, битов) не прописывать, так как они должны быть в стандартных файлах.

**Comment by trol73** [comment]
Сделал, но только для констант.
SPL - не валидное значение для листинга, листинг показывает чистый машинный код.  И по этому коду надо, в том числе, иметь возможность понять, что имена регистров верно оттранслировались в их адреса. И при просмотре листинга в правой панели всегда можно видеть исходный код с именами в панели левой (условно) .

**Comment by Vadimatorik** [comment]
Ну хотя бы так. Спасибо)
