### ISSUE TITLE
[ОШИБКА] Работа препроцессора для макросов в define

### ISSUE THREAD

**Issue by Vadimatorik** [trol73/the-rat-avr#7]
Этот код не собирается:

```
use r16 as tr1

#define SET_STACK_POINTER() SPL = tr1 = 0x60

proc main() {
    SET_STACK_POINTER()
}
```

**Comment by Vadimatorik** [comment]
SPL = tr1 - собирается
tr1 = 0x60 - нет)
Это если макрос кастрировать с одной их сторон)

**Comment by trol73** [comment]
Если убрать скобки, то соберется
```
use r16 as tr1

#define SET_STACK_POINTER() SPL = tr1 = 0x60

proc main() {
    SET_STACK_POINTER
}
```

**Comment by Vadimatorik** [comment]
Так должно собираться и с ними. В этом и суть. "типа это функция") В С рабочая тема. Хоть inline и во всем лучше.

**Comment by trol73** [comment]
Да, это точно баг, согласен )
Но быстро починить пока не получилось

**Comment by trol73** [comment]
Исправил. В следующем обновлении будет

**Comment by trol73** [comment]
Откатил исправление - оно приводит к зависанию

**Comment by Vadimatorik** [comment]
Неплохо!) Ну, это даже по-своему забавно)
