### ISSUE TITLE
[ОШИБКА] Обязательно требуется указать device в коде. Из среды не работает

### ISSUE THREAD

**Issue by Vadimatorik** [trol73/the-rat-avr#8]
![image](https://user-images.githubusercontent.com/14297516/222750930-8738a8f9-70cb-43d4-94ef-60778b8b235b.png)

**Comment by Vadimatorik** [comment]
Если пропишу в коде как раньше, когда тут было none - все хорошо.

**Comment by trol73** [comment]
Это репозиторий компилятора, не IDE :)
