### ISSUE TITLE
[ЖЕЛАЕМОЕ ИСПРАВЛЕНИЕ] Среда не передает сборщику все пути. А передает только указанный корневой

### ISSUE THREAD

**Issue by Vadimatorik** [trol73/the-rat-avr#9]
Из-за этого в include приходится писать полный путь. Хотелось бы, чтобы происходил рекурсивный проход под директориям ниже текущей и автоматическое их добавление к сборке.

**Comment by trol73** [comment]
В локальном файле конфигурации можно указать все необходимые пути. Как вариант, можно еще автоматизировать это через скрипт сборщика.
Автоматическое добавление всех путей - неочевидная штука, которая может привести к путанице, кмк.
